# ===================================
#  Relation Behavior Config
# ===================================

_default_config:
    label: Relation

    # Columns supplied dynamically
    list: []

    # Fields supplied dynamically
    form: []
