<?php return array (
  'providers' => 
  array (
    0 => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    1 => 'Illuminate\\Bus\\BusServiceProvider',
    2 => 'Illuminate\\Cache\\CacheServiceProvider',
    3 => 'Illuminate\\Cookie\\CookieServiceProvider',
    4 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    5 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    6 => 'Illuminate\\Hashing\\HashServiceProvider',
    7 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    8 => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    9 => 'Illuminate\\Queue\\QueueServiceProvider',
    10 => 'Illuminate\\Redis\\RedisServiceProvider',
    11 => 'Illuminate\\Session\\SessionServiceProvider',
    12 => 'Illuminate\\View\\ViewServiceProvider',
    13 => 'October\\Rain\\Foundation\\Providers\\AppSupportServiceProvider',
    14 => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    15 => 'Laravel\\Tinker\\TinkerServiceProvider',
    16 => 'Carbon\\Laravel\\ServiceProvider',
    17 => 'Termwind\\Laravel\\TermwindServiceProvider',
    18 => 'October\\Rain\\Foundation\\Providers\\AppSupportServiceProvider',
    19 => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    20 => 'Laravel\\Tinker\\TinkerServiceProvider',
    21 => 'System\\ServiceProvider',
  ),
  'eager' => 
  array (
    0 => 'Illuminate\\Cookie\\CookieServiceProvider',
    1 => 'Illuminate\\Encryption\\EncryptionServiceProvider',
    2 => 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider',
    3 => 'Illuminate\\Pagination\\PaginationServiceProvider',
    4 => 'Illuminate\\Session\\SessionServiceProvider',
    5 => 'Illuminate\\View\\ViewServiceProvider',
    6 => 'October\\Rain\\Foundation\\Providers\\AppSupportServiceProvider',
    7 => 'Carbon\\Laravel\\ServiceProvider',
    8 => 'Termwind\\Laravel\\TermwindServiceProvider',
    9 => 'October\\Rain\\Foundation\\Providers\\AppSupportServiceProvider',
    10 => 'System\\ServiceProvider',
  ),
  'deferred' => 
  array (
    'Illuminate\\Broadcasting\\BroadcastManager' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Contracts\\Broadcasting\\Factory' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Contracts\\Broadcasting\\Broadcaster' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider',
    'Illuminate\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Contracts\\Bus\\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Contracts\\Bus\\QueueingDispatcher' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Bus\\BatchRepository' => 'Illuminate\\Bus\\BusServiceProvider',
    'Illuminate\\Bus\\DatabaseBatchRepository' => 'Illuminate\\Bus\\BusServiceProvider',
    'cache' => 'Illuminate\\Cache\\CacheServiceProvider',
    'cache.store' => 'Illuminate\\Cache\\CacheServiceProvider',
    'cache.psr6' => 'Illuminate\\Cache\\CacheServiceProvider',
    'memcached.connector' => 'Illuminate\\Cache\\CacheServiceProvider',
    'Illuminate\\Cache\\RateLimiter' => 'Illuminate\\Cache\\CacheServiceProvider',
    'hash' => 'Illuminate\\Hashing\\HashServiceProvider',
    'hash.driver' => 'Illuminate\\Hashing\\HashServiceProvider',
    'Illuminate\\Contracts\\Pipeline\\Hub' => 'Illuminate\\Pipeline\\PipelineServiceProvider',
    'queue' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.connection' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.failer' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.listener' => 'Illuminate\\Queue\\QueueServiceProvider',
    'queue.worker' => 'Illuminate\\Queue\\QueueServiceProvider',
    'redis' => 'Illuminate\\Redis\\RedisServiceProvider',
    'redis.connection' => 'Illuminate\\Redis\\RedisServiceProvider',
    'mail.manager' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'mailer' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Mail\\Markdown' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'html' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'form' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'block' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'flash' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'parse.markdown' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'parse.yaml' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'parse.twig' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'parse.ini' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'assetic' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'resizer' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'validator' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'validation.presence' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'translator' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'translation.loader' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Cache\\Console\\ClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Cache\\Console\\ForgetCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'October\\Rain\\Foundation\\Console\\ClearCompiledCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\ConfigCacheCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\ConfigClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\WipeCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\DownCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\EnvironmentCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\EventCacheCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\EventClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\EventListCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\KeyGenerateCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\OptimizeCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\OptimizeClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\PackageDiscoverCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\ClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\ListFailedCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\FlushFailedCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\ForgetFailedCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\ListenCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\MonitorCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\PruneBatchesCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\PruneFailedJobsCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\RestartCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\RetryCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\RetryBatchCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Queue\\Console\\WorkCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'October\\Rain\\Foundation\\Console\\RouteCacheCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\RouteClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'October\\Rain\\Foundation\\Console\\RouteListCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Console\\Scheduling\\ScheduleFinishCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Console\\Scheduling\\ScheduleListCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Console\\Scheduling\\ScheduleRunCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Console\\Scheduling\\ScheduleClearCacheCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Console\\Scheduling\\ScheduleTestCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Console\\Scheduling\\ScheduleWorkCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Seeds\\SeedCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\StorageLinkCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\UpCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\ViewCacheCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\ViewClearCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'October\\Rain\\Foundation\\Console\\ProjectSetCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'October\\Rain\\Foundation\\Console\\ServeCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Foundation\\Console\\VendorPublishCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'migrator' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'migration.repository' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'migration.creator' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\MigrateCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\FreshCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\InstallCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\RefreshCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\ResetCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\RollbackCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\StatusCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'Illuminate\\Database\\Console\\Migrations\\MigrateMakeCommand' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.plugin' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.model' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.migration' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.controller' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.component' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.formwidget' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.reportwidget' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.filterwidget' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.contentfield' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.command' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.test' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.job' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.factory' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.create.seeder' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'composer' => 'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider',
    'command.tinker' => 'Laravel\\Tinker\\TinkerServiceProvider',
  ),
  'when' => 
  array (
    'Illuminate\\Broadcasting\\BroadcastServiceProvider' => 
    array (
    ),
    'Illuminate\\Bus\\BusServiceProvider' => 
    array (
    ),
    'Illuminate\\Cache\\CacheServiceProvider' => 
    array (
    ),
    'Illuminate\\Hashing\\HashServiceProvider' => 
    array (
    ),
    'Illuminate\\Pipeline\\PipelineServiceProvider' => 
    array (
    ),
    'Illuminate\\Queue\\QueueServiceProvider' => 
    array (
    ),
    'Illuminate\\Redis\\RedisServiceProvider' => 
    array (
    ),
    'October\\Rain\\Foundation\\Providers\\AppDeferSupportServiceProvider' => 
    array (
    ),
    'Laravel\\Tinker\\TinkerServiceProvider' => 
    array (
    ),
  ),
);